package handlers

import (
	"backend/config"
	"backend/internal/models"
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateProduct now expects a JSON body with the ImageURL already generated by Vercel
func CreateProduct(c *gin.Context) {
	var input struct {
		Name        string  `json:"name"`
		SKU         string  `json:"sku"`
		Description string  `json:"description"`
		Price       float64 `json:"price"`
		StockQty    int     `json:"stock_qty"`
		ImageURL    string  `json:"image_url"` // Frontend sends this
	}

	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	product := models.Product{
		Name:        input.Name,
		SKU:         input.SKU,
		Description: input.Description,
		Price:       input.Price,
		StockQty:    input.StockQty,
		ImageURL:    input.ImageURL,
	}

	if err := config.DB.Create(&product).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create product"})
		return
	}

	c.JSON(http.StatusCreated, product)
}

func GetProducts(c *gin.Context) {
	var products []models.Product
	config.DB.Find(&products)
	c.JSON(http.StatusOK, products)
}

// DeleteProduct deletes a product by ID (admin only)
func DeleteProduct(c *gin.Context) {
	id := c.Param("id")

	var product models.Product
	if err := config.DB.First(&product, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Product not found"})
		return
	}

	if err := config.DB.Delete(&product).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to delete product"})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": "Product deleted successfully"})
}
